import type { Metadata } from "next";
import { Roboto, Oswald } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ['300','400','500','700'],
  variable:"--font-roboto"
});
const oswald = Oswald({
  subsets: ["cyrillic"],
  weight: ['500','600','700'],
  variable:"--font-oswalid"
});

export const metadata: Metadata = {
  title: "GamingShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${rpbptp.variable} ${osvald.variable} w-full bg-сontain  bg-full bg-no-repeat bg-hero text-white' }>
        <div className="__next">
          <Header />
            <main className="main w-full bg-bg bg-cover bg-center bg-no-repeat" id="main">
              <div className="w-full" id="mainPage">
              {children}
              </div>
            </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
